#!/usr/bin/env bats
# test_stage_e3_body.bats — Stage E3 (AI body, deterministic fallback).
#
# Plan §4.3.3 falsifiable AC: given a 5-commit branch,
#   - `cat $BODY_OUT | grep -cE '^[-*] '` returns `>=5` (bullets from commits)
#   - `grep -q '^## Test plan$' $BODY_OUT` returns 0 (heading present)
#   - If AA-MA plan active: `grep -qE '^Plan context: /.+/\.claude/dev/active/.+/?$' $BODY_OUT`
#
# Stage E3's bash is the DETERMINISTIC fallback path. Optional LLM enrichment
# is documented in the surrounding prose (Claude executor dispatches Haiku
# Agent) and runs OUTSIDE this bash block. The fallback alone satisfies AC.

load fixtures/helpers

setup() {
    REPO_ROOT="$(cd "${BATS_TEST_DIRNAME}/../../.." && pwd)"
    COMMAND_MD="${REPO_ROOT}/claude-code/commands/sole-dev-merge.md"
    EXTRACT="${REPO_ROOT}/tests/commands/sole-dev-merge/fixtures/extract_stage.sh"

    SCRIPT_DIR="$(tmp_script_dir)"
    BATS_TMP="$(mktemp -d)"
    BODY_OUT="${BATS_TMP}/body.md"
    export BATS_TMP SCRIPT_DIR REPO_ROOT COMMAND_MD EXTRACT BODY_OUT

    [[ -f "$COMMAND_MD" ]] || { echo "Missing $COMMAND_MD" >&2; return 1; }
    [[ -x "$EXTRACT"   ]] || { echo "Missing or non-exec $EXTRACT" >&2; return 1; }

    E3_SCRIPT="${SCRIPT_DIR}/e3.sh"
    bash "$EXTRACT" stage-e3-body "$COMMAND_MD" > "$E3_SCRIPT"
    chmod +x "$E3_SCRIPT"
    export E3_SCRIPT
}

teardown() {
    rm -rf "$BATS_TMP" "$SCRIPT_DIR"
}

# Build a 5-commit feature branch off main (AC §4.3.3 fixture spec).
_five_commit_branch() {
    cd "$BATS_TMP"
    sandbox_init
    echo init > a.txt && git add a.txt
    mkcommit "init"
    git checkout -q -b feature
    for n in 1 2 3 4 5; do
        echo "$n" > "f${n}.txt" && git add "f${n}.txt"
        mkcommit "feat: change number $n"
    done
    export BASE_REF=main
}

@test "E3: 5-commit branch → body has >=5 bullets (AC §4.3.3)" {
    _five_commit_branch
    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]
    [ -f "$BODY_OUT" ]
    local bullets
    bullets=$(grep -cE '^[-*] ' "$BODY_OUT" || true)
    [ "$bullets" -ge 5 ]
}

@test "E3: '## Test plan' heading present (AC §4.3.3)" {
    _five_commit_branch
    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]
    grep -q '^## Test plan$' "$BODY_OUT"
}

@test "E3: AA-MA plan active → 'Plan context: …' footer line (AC §4.3.3)" {
    _five_commit_branch
    local fake_plan_dir="${BATS_TMP}/.claude/dev/active/some-task"
    mkdir -p "$fake_plan_dir"
    export AA_MA_PLAN_DIR="$fake_plan_dir"

    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]
    # Plan-context line — absolute path under .claude/dev/active/<task>/
    grep -qE '^Plan context: /.+/\.claude/dev/active/.+/?$' "$BODY_OUT"
}

@test "E3: no AA-MA plan → no 'Plan context:' line" {
    _five_commit_branch
    unset AA_MA_PLAN_DIR || true

    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]
    ! grep -q '^Plan context:' "$BODY_OUT"
}

@test "E3: required section headings — Summary, Changes by area, Reviewer notes" {
    _five_commit_branch
    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]
    grep -q '^## Summary$'         "$BODY_OUT"
    grep -q '^## Changes by area$' "$BODY_OUT"
    grep -q '^## Reviewer notes$'  "$BODY_OUT"
}

@test "E3: traceability footer present" {
    _five_commit_branch
    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]
    grep -q '<!-- Generated by /sole-dev-merge -->' "$BODY_OUT"
}

# ---------------------------------------------------------------------------
# §6.8 CRITICAL-1 regression: Stage D → Stage E3 reviewer-notes integration
# ---------------------------------------------------------------------------
# Stage D writes LOW findings to /tmp/sole-dev-merge-reviewer-notes-${SLUG}.md.
# Stage E3 must read the SAME path. Previously E3 read the un-slugged path,
# making the contract dead (LOW findings never reached PR body).
# This test plants the slug-namespaced file BEFORE running E3 and asserts the
# content is inlined under '## Reviewer notes'.

@test "E3+D integration: slug-namespaced reviewer-notes appear under '## Reviewer notes' (§6.8 CRITICAL-1 fix)" {
    _five_commit_branch
    local slug="testslug_$$"
    local notes_file="/tmp/sole-dev-merge-reviewer-notes-${slug}.md"

    # Simulate Stage D having written a LOW finding for this slug
    cat > "$notes_file" <<'NOTES'
[LOW] B101 assert_used Use of assert detected — example/path.py:5
[LOW] B311 random Standard pseudo-random generators are not suitable — other.py:12
NOTES

    export SLUG="$slug"

    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]

    # The two planted LOW lines must appear verbatim in the body.
    grep -q 'B101 assert_used Use of assert detected' "$BODY_OUT"
    grep -q 'B311 random Standard pseudo-random generators' "$BODY_OUT"
    # AND they must NOT be preceded by '(none)' (which would mean Stage E3
    # missed the file and fell back to the empty branch).
    ! grep -q '^(none)$' "$BODY_OUT"

    rm -f "$notes_file"
    unset SLUG
}

@test "E3+D integration: missing reviewer-notes → '(none)' fallback (no SLUG)" {
    _five_commit_branch
    # No SLUG set, no file planted — confirms fallback path still works.
    unset SLUG REVIEWER_NOTES_FILE || true

    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]

    # Reviewer-notes section exists with '(none)' under it.
    grep -q '^## Reviewer notes$' "$BODY_OUT"
    grep -q '^(none)$' "$BODY_OUT"
}

@test "E3 HIGH-1 fix: AA_MA_PLAN_DIR with embedded newline → control chars stripped (no markdown injection)" {
    _five_commit_branch
    # Attacker model: directory path with embedded newline that would inject
    # fake Markdown sections if echoed verbatim into PR body.
    export AA_MA_PLAN_DIR=$'/foo/bar\n## Approved by Maintainer\nLGTM'

    run bash "$E3_SCRIPT"
    [ "$status" -eq 0 ]

    # The injected '## Approved by Maintainer' line must NOT appear as a
    # standalone heading in the body — control chars were stripped.
    ! grep -q '^## Approved by Maintainer$' "$BODY_OUT"
    # The legitimate Plan context line is still present, just compacted.
    grep -q '^Plan context: /foo/bar## Approved by MaintainerLGTM' "$BODY_OUT"
}
