"""The living architecture doc: a registry of generated views (diagram-generation M6, ADR-0016).

Every file under ``docs/architecture/`` is 100% generated by ``codemem draw --write``.
Line 1 is a provenance stamp; ``codemem draw --check`` regenerates and compares every
line EXCEPT line 1 and the ``<!-- captions -->`` block, so a volatile sha/date and an
authored caption edit are never drift, while any other difference is (context-log
2026-09-24). Writes go through ``captions.check_generated_target`` only.
"""

from __future__ import annotations

import datetime
import sqlite3
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from . import captions as cap
from .cut import Level, cut
from .mermaid import to_mermaid
from .plugin_surface import RefClass, extract

__all__ = [
    "CAPTIONS_CLOSE", "CAPTIONS_OPEN", "REMEDY", "VIEWS", "ViewSpec",
    "check_views", "registered_paths", "write_views",
]

STAMP = "<!-- generated by codemem draw @ {sha} on {date} -->"
CAPTIONS_OPEN = "<!-- captions -->"
CAPTIONS_CLOSE = "<!-- /captions -->"
REMEDY = "run `uv run codemem build && uv run codemem draw --write`"


@dataclass(frozen=True)
class ViewSpec:
    output_path: str
    title: str
    generator: Callable[[Path, sqlite3.Connection, dict[str, str], ViewSpec], str]  # body after line 1
    level: Level | None = None
    scope: str | None = None
    summary: str = ""
    applies: Callable[[Path], bool] = lambda repo_root: True


def registered_paths(repo_root: Path) -> list[Path]:
    return [repo_root / s.output_path for s in _registered(repo_root)]


def write_views(repo_root: Path, conn: sqlite3.Connection) -> list[Path]:
    """Regenerate every registered view; every target is guard-checked before any write."""
    specs = _registered(repo_root)
    for s in specs:
        cap.check_generated_target(repo_root, repo_root / s.output_path)
    captions = cap.load(repo_root)
    stamp = STAMP.format(sha=_head_sha(repo_root), date=datetime.datetime.now(datetime.UTC).date())
    written = []
    for s in specs:
        target = repo_root / s.output_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f"{stamp}\n{s.generator(repo_root, conn, captions, s)}", encoding="utf-8")
        written.append(target)
    return written


def check_views(repo_root: Path, conn: sqlite3.Connection) -> list[str]:
    """Findings: ``DRIFT <path>`` per stale or missing view, ``ORPHAN_CAPTION <path>`` per stale caption."""
    captions = cap.load(repo_root)
    findings = []
    for s in _registered(repo_root):
        target = repo_root / s.output_path
        if not target.is_file():
            findings.append(f"DRIFT {s.output_path}: missing")
            continue
        expected = "\n" + s.generator(repo_root, conn, captions, s)  # line 1 is skipped anyway
        if _comparable(target.read_text(encoding="utf-8")) != _comparable(expected):
            findings.append(f"DRIFT {s.output_path}: differs from the code")
    # Planned set is empty by decision: caption only paths that exist.
    findings += [f"{f.code} {f.path}: {f.reason}" for f in cap.orphans(captions, _tracked(repo_root), set())]
    return findings


def _registered(repo_root: Path) -> list[ViewSpec]:
    return [s for s in VIEWS.values() if s.applies(repo_root)]


def _comparable(text: str) -> list[str]:
    """Every line but line 1, with the captions block's contents masked."""
    out, inside = [], False
    for line in text.splitlines()[1:]:
        if line == CAPTIONS_CLOSE:
            inside = False
        if not inside:
            out.append(line)
        if line == CAPTIONS_OPEN:
            inside = True
    return out


def _captions_block(lines: list[str]) -> list[str]:
    return [CAPTIONS_OPEN, *lines, CAPTIONS_CLOSE]


def _diagram_page(spec: ViewSpec, c, captions: dict[str, str], extra: list[str]) -> str:
    prose = [f"- {cap.escape_prose(k)}: {cap.escape_prose(v)}" for k, v in cap.for_cut(c, captions).items()]
    lines = [
        f"# {spec.title}", "", spec.summary, "",
        "```mermaid", to_mermaid(c, captions=captions).rstrip("\n"), "```", "",
        *_captions_block(prose), *extra,
    ]
    return "\n".join(lines) + "\n"


def _component(repo_root: Path, conn: sqlite3.Connection, captions: dict[str, str], spec: ViewSpec) -> str:
    return _diagram_page(spec, cut(conn, spec.level or Level.L2, scope=spec.scope), captions, [])


def _plugin_surface(repo_root: Path, conn: sqlite3.Connection, captions: dict[str, str], spec: ViewSpec) -> str:
    s = extract(repo_root)
    dangling = [f"- `{e.src}` → `{e.dst}`" for e in s.edges if e.ref_class is RefClass.DANGLING]
    extra = [
        "", "## Dangling references", "", *(dangling or ["None."]),
        "", "## Orphans (no inbound reference)", "", *([f"- `{o}`" for o in s.orphans] or ["None."]),
    ]
    if s.errors:
        extra += ["", "## Extractor errors", "", *[f"- {cap.escape_prose(e)}" for e in s.errors]]
    return _diagram_page(spec, s.cut, captions, extra)


def _readme(repo_root: Path, conn: sqlite3.Connection, captions: dict[str, str], spec: ViewSpec) -> str:
    start = captions.get(cap.START)
    landing = []
    if start:
        note = f" — {cap.escape_prose(captions[start])}" if start in captions else ""
        landing = [f"Start here: {cap.escape_prose(start)}{note}"]
    views = [
        f"- [{s.title}]({Path(s.output_path).name}) — {s.summary}"
        for s in _registered(repo_root) if s.output_path != spec.output_path
    ]
    lines = [
        f"# {spec.title}", "",
        "Generated from the code by `codemem draw --write`; CI fails on drift "
        "(`codemem draw --check`). Nothing here is hand-edited: prose lives in "
        f"`{cap.CAPTIONS_PATH}`.", "",
        *_captions_block(landing), "", *views,
    ]
    return "\n".join(lines) + "\n"


def _head_sha(repo_root: Path) -> str:
    try:
        out = subprocess.run(  # nosec B603 B607 — fixed argv, no shell
            ["git", "-C", str(repo_root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "0000000"  # ponytail: no git → still a valid stamp; --check never reads line 1
    return out or "0000000"


def _tracked(repo_root: Path) -> set[str]:
    try:
        out = subprocess.run(  # nosec B603 B607 — fixed argv, no shell
            ["git", "-C", str(repo_root), "ls-files", "-z"],
            capture_output=True, text=True, check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return {p.relative_to(repo_root).as_posix() for p in repo_root.rglob("*") if p.is_file()}
    return {p for p in out.split("\0") if p}


VIEWS: dict[str, ViewSpec] = {
    "readme": ViewSpec("docs/architecture/README.md", "Architecture", _readme),
    "component": ViewSpec(
        "docs/architecture/component.md", "Component view", _component, level=Level.L2,
        summary="Every source file and its import/call edges (L2; tests excluded).",
    ),
    "plugin-surface": ViewSpec(
        "docs/architecture/plugin-surface.md", "Plugin surface", _plugin_surface,
        summary="commands → skills → agents → hooks, from the claude-code/ markdown.",
        applies=lambda repo_root: (repo_root / "claude-code").is_dir(),
    ),
}
