"""codemem.draw.cut — layered cuts L0–L3 (diagram-generation M3).

Fidelity: the prototype's bands (Ticket 3) were measured on call edges at
c49d084. ``tests/fixtures/draw-prototype-graph.json`` is that exact data, so the
port is pinned against it rather than against today's (larger) repo.
"""

from __future__ import annotations

import json
import sqlite3
from collections.abc import Sequence
from pathlib import Path

import pytest

from codemem.draw.cut import MAX_EDGES, Cut, Level, cut, is_test_path, node_id
from codemem.storage.db import connect, ensure_schema

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"


# ---------------------------------------------------------------------
# node_id — the contract M12's JS must reproduce byte-for-byte
# ---------------------------------------------------------------------

def _node_ids() -> list[dict]:
    return json.loads((FIXTURES / "draw-node-ids.json").read_text(encoding="utf-8"))


def test_node_id_round_trips_js_fixture() -> None:
    """The fixture is generated by an independent JS port of the prototype hash."""
    mismatches = [
        (e["level"], e["name"], e["id"], node_id(e["name"], Level(e["level"])))
        for e in _node_ids()
        if node_id(e["name"], Level(e["level"])) != e["id"]
    ]
    assert mismatches == []


def test_node_ids_unique_within_and_across_levels() -> None:
    entries = _node_ids()
    assert len({e["id"] for e in entries}) == len(entries)
    assert {e["level"] for e in entries} == {0, 1, 2, 3}


def test_node_id_is_mermaid_safe() -> None:
    for e in _node_ids():
        assert e["id"].isalnum() and e["id"][0] == "n"


# ---------------------------------------------------------------------
# Fixture DBs
# ---------------------------------------------------------------------

def _db(tmp_path: Path, calls: Sequence[tuple[str, str, str, str]],
        imports: Sequence[tuple[str, str]] = (), extra_files: Sequence[str] = ()) -> sqlite3.Connection:
    """Real codemem schema; symbols keyed (file, name) as the prototype keyed them."""
    conn = connect(tmp_path / "idx.db")
    ensure_schema(conn)
    paths = sorted({p for sf, _, df, _ in calls for p in (sf, df)}
                   | {p for e in imports for p in e} | set(extra_files))
    fid = {}
    for p in paths:
        fid[p] = conn.execute(
            "INSERT INTO files(path, lang, last_indexed) VALUES (?, 'python', 0)", (p,)
        ).lastrowid
    sid = {}
    for f, s in sorted({(sf, ss) for sf, ss, _, _ in calls} | {(df, ds) for _, _, df, ds in calls}):
        sid[(f, s)] = conn.execute(
            "INSERT INTO symbols(file_id, scip_id, name, kind) VALUES (?, ?, ?, 'function')",
            (fid[f], f"codemem . /{f}#{s}", s.rsplit(".", 1)[-1]),
        ).lastrowid
    for sf, ss, df, ds in calls:  # duplicates kept on purpose: production stores every row twice
        conn.execute(
            "INSERT INTO edges(src_symbol_id, dst_symbol_id, kind) VALUES (?, ?, 'call')",
            (sid[(sf, ss)], sid[(df, ds)]),
        )
    for a, b in imports:
        conn.execute(
            "INSERT INTO file_edges(src_file_id, dst_file_id, kind) VALUES (?, ?, 'import')",
            (fid[a], fid[b]),
        )
    conn.commit()
    return conn


@pytest.fixture(scope="module")
def proto(tmp_path_factory) -> sqlite3.Connection:
    g = json.loads((FIXTURES / "draw-prototype-graph.json").read_text(encoding="utf-8"))
    return _db(tmp_path_factory.mktemp("proto"), [tuple(e) for e in g["edges"]],
               extra_files=g["files"])


def _nc(c: Cut) -> tuple[int, int]:
    return len(c.nodes), len(c.edges)


# ---------------------------------------------------------------------
# Fidelity — every Ticket 3 band, on the data it was measured on
# ---------------------------------------------------------------------

class TestPrototypeFidelity:
    def test_raw_file_level_with_tests(self, proto) -> None:
        assert _nc(cut(proto, Level.L2, include_tests=True, kind="call")) == (85, 96)

    def test_raw_file_level_without_tests(self, proto) -> None:
        assert _nc(cut(proto, Level.L2, kind="call")) == (25, 27)

    def test_l0_top_dirs_with_tests(self, proto) -> None:
        assert _nc(cut(proto, Level.L0, include_tests=True, kind="call")) == (4, 3)

    def test_l1_depth2_with_tests(self, proto) -> None:
        assert _nc(cut(proto, Level.L1, include_tests=True, kind="call")) == (10, 9)

    def test_l2_scoped_render_one_hop_both(self, proto) -> None:
        c = cut(proto, Level.L2, scope="src/aa_ma/render/", hops=1, kind="call")
        assert _nc(c) == (5, 4)

    def test_l3_symbols_gate_one_hop_down(self, proto) -> None:
        c = cut(proto, Level.L3, scope="src/aa_ma/gate.py", hops=1, direction="down")
        assert _nc(c) == (18, 27)

    def test_tests_excluded_by_default_at_every_level(self, proto) -> None:
        for level in Level:
            c = cut(proto, level, scope="src/" if level is Level.L3 else None)
            assert not any(is_test_path(n) for n in c.nodes.values()), level


# ---------------------------------------------------------------------
# Semantics on small hand-built graphs
# ---------------------------------------------------------------------

CALLS = [
    ("src/a.py", "f", "src/b.py", "g"),
    ("src/a.py", "f", "src/b.py", "g"),           # stored twice, as in production
    ("src/b.py", "g", "lib/c.py", "h"),
    ("src/a.py", "f", "src/a.py", "local"),       # same-file: never a file edge
    ("tests/test_a.py", "t", "src/a.py", "f"),
]
IMPORTS = [("src/a.py", "src/b.py"), ("lib/c.py", "src/b.py")]


@pytest.fixture
def small(tmp_path: Path) -> sqlite3.Connection:
    return _db(tmp_path, CALLS, IMPORTS)


class TestSemantics:
    def test_both_kinds_labelled(self, small) -> None:
        c = cut(small, Level.L2)
        by_name = {(c.nodes[a], c.nodes[b], k) for a, b, k in c.edges}
        assert by_name == {
            ("src/a.py", "src/b.py", "call"), ("src/b.py", "lib/c.py", "call"),
            ("src/a.py", "src/b.py", "import"), ("lib/c.py", "src/b.py", "import"),
        }

    @pytest.mark.parametrize(("kind", "expected"), [("call", {"call"}), ("import", {"import"})])
    def test_kind_filter(self, small, kind, expected) -> None:
        assert {k for _, _, k in cut(small, Level.L2, kind=kind).edges} == expected

    def test_duplicate_rows_do_not_double(self, small) -> None:
        assert len(cut(small, Level.L2, kind="call").edges) == 2

    def test_include_tests(self, small) -> None:
        assert "tests/test_a.py" in cut(small, Level.L2, include_tests=True).nodes.values()

    def test_l0_collapses_to_top_dirs(self, small) -> None:
        c = cut(small, Level.L0)
        assert set(c.nodes.values()) == {"src", "lib"}

    @pytest.mark.parametrize(("direction", "expected"), [
        ("down", {("src/b.py", "lib/c.py")}),
        ("up", {("src/a.py", "src/b.py")}),
        ("both", {("src/a.py", "src/b.py"), ("src/b.py", "lib/c.py")}),
    ])
    def test_direction(self, small, direction, expected) -> None:
        c = cut(small, Level.L2, scope="src/b.py", kind="call", direction=direction)
        assert {(c.nodes[a], c.nodes[b]) for a, b, _ in c.edges} == expected

    def test_hops_two_reaches_further(self, small) -> None:
        c = cut(small, Level.L2, scope="src/a.py", kind="call", hops=2, direction="down")
        assert {c.nodes[b] for _, b, _ in c.edges} == {"src/b.py", "lib/c.py"}

    def test_l3_is_call_only(self, small) -> None:
        c = cut(small, Level.L3, scope="src/", kind="both")
        assert {k for _, _, k in c.edges} == {"call"}

    def test_node_keys_are_node_ids(self, small) -> None:
        c = cut(small, Level.L2)
        assert all(k == node_id(v, Level.L2) for k, v in c.nodes.items())

    def test_over_ceiling_reports_dropped(self, tmp_path: Path) -> None:
        calls = [("src/hub.py", "f", f"src/m{i}.py", "g") for i in range(MAX_EDGES + 7)]
        c = cut(_db(tmp_path, calls), Level.L2)
        assert len(c.edges) == MAX_EDGES
        assert c.dropped == 7

    def test_invalid_direction_rejected(self, small) -> None:
        with pytest.raises(ValueError):
            cut(small, Level.L2, direction="sideways")


@pytest.mark.parametrize(("path", "expected"), [
    ("tests/test_a.py", True),
    ("packages/x/tests/test_b.py", True),
    ("src/tests_helper.py", False),
    ("src/attests/x.py", False),
])
def test_is_test_path(path, expected) -> None:
    assert is_test_path(path) is expected


def test_l3_import_kind_rejected(small) -> None:
    """L3 is symbol-level calls only; asking for imports there is an error, not an empty diagram."""
    with pytest.raises(ValueError):
        cut(small, Level.L3, kind="import")


# ---------------------------------------------------------------------
# Repeatable --scope (diagram-generation M10: /aa-ma-plan seeds §13 from several files)
# ---------------------------------------------------------------------

def test_several_scopes_are_one_union_cut(proto) -> None:
    one = cut(proto, Level.L2, scope="src/aa_ma/render/", hops=1)
    two = cut(proto, Level.L2, scope="src/aa_ma/gate.py", hops=1)
    both = cut(proto, Level.L2, scope=("src/aa_ma/render/", "src/aa_ma/gate.py"), hops=1)
    assert both.edges == one.edges | two.edges
    assert set(both.nodes) == set(one.nodes) | set(two.nodes)


def test_cli_scope_is_repeatable(proto, tmp_path, monkeypatch, capsys) -> None:
    from codemem.cli import main

    db = tmp_path / "p.db"
    with sqlite3.connect(db) as out:
        proto.backup(out)
    args = ["--db", str(db), "draw", "--level", "L2", "--hops", "1"]
    assert main([*args, "--scope", "src/aa_ma/render/", "--scope", "src/aa_ma/gate.py"]) == 0
    both = capsys.readouterr().out
    assert main([*args, "--scope", "src/aa_ma/render/"]) == 0
    one = capsys.readouterr().out
    assert main([*args, "--scope", "src/aa_ma/gate.py"]) == 0
    two = capsys.readouterr().out
    assert set(both.splitlines()) == set(one.splitlines()) | set(two.splitlines())
