"""codemem draw --write / --check — the living architecture doc (diagram-generation M6).

Decisions (context-log 2026-09-24): component = L2 whole repo; `--write` regenerates,
`--check` compares every line except line 1 (the stamp) and the `<!-- captions -->`
block; `ORPHAN_CAPTION` against `git ls-files` with an empty planned set.
"""

from __future__ import annotations

import json
import re
import sqlite3
import subprocess
from pathlib import Path

import pytest
import yaml

from codemem.cli import main
from codemem.draw import views
from codemem.draw.captions import CAPTIONS_PATH
from codemem.indexer import build_index

STAMP = re.compile(r"^<!-- generated by codemem draw @ [0-9a-f]{7,40} on \d{4}-\d{2}-\d{2} -->$")
REPO = Path(__file__).resolve().parents[2]


def _git(root: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(root), *args], check=True, capture_output=True)


@pytest.fixture
def repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A committed two-package repo with an index at the default location, cwd inside it."""
    root = tmp_path / "r"
    (root / "pkg").mkdir(parents=True)
    (root / "pkg/__init__.py").write_text("")
    (root / "pkg/a.py").write_text("from pkg import b\n\ndef run():\n    return b.helper()\n")
    (root / "pkg/b.py").write_text("def helper():\n    return 1\n")
    (root / "lib").mkdir()
    (root / "lib/__init__.py").write_text("")
    (root / "lib/c.py").write_text("from pkg import a\n\ndef go():\n    return a.run()\n")
    (root / CAPTIONS_PATH).parent.mkdir(parents=True)
    (root / CAPTIONS_PATH).write_text(json.dumps({"@start": "pkg/a.py", "pkg/": "The package."}))
    _git(root, "init", "-q")
    _git(root, "add", ".")
    _git(root, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "init")
    build_index(root, root / ".codemem/index.db", package=".")
    monkeypatch.chdir(root)
    return root


def _draw(*flags: str) -> int:
    return main(["draw", *flags])


def _files(root: Path) -> dict[Path, str]:
    return {p: p.read_text() for p in views.registered_paths(root)}


# ---------------------------------------------------------------------
# --write (AC1) and the registry
# ---------------------------------------------------------------------

def test_write_generates_every_registered_view_with_a_stamp(repo: Path) -> None:
    assert _draw("--write") == 0
    paths = views.registered_paths(repo)
    assert {p.name for p in paths} == {"README.md", "component.md"}  # no claude-code/ here
    for p in paths:
        assert p.is_relative_to(repo / "docs/architecture")
        assert STAMP.match(p.read_text().splitlines()[0]), p


def test_rewrite_changes_nothing_but_line_1(repo: Path) -> None:
    _draw("--write")
    before = _files(repo)
    _draw("--write")
    for p, text in _files(repo).items():
        assert text.splitlines()[1:] == before[p].splitlines()[1:]
        assert STAMP.match(text.splitlines()[0])


def test_component_view_is_l2_with_start_highlight_and_escaped_captions(repo: Path) -> None:
    (repo / CAPTIONS_PATH).write_text(json.dumps({"@start": "pkg/a.py", "pkg/": "```mermaid\n# x"}))
    _draw("--write")
    text = (repo / "docs/architecture/component.md").read_text()
    assert '["pkg/a.py"]' in text and '["lib/c.py"]' in text  # L2 = file nodes
    assert "classDef start" in text
    block = text.split(views.CAPTIONS_OPEN, 1)[1].split(views.CAPTIONS_CLOSE, 1)[0]
    assert "\\```mermaid # x" in block  # escape_prose: one inert line


def test_plugin_surface_registers_only_where_claude_code_exists(repo: Path) -> None:
    assert "plugin-surface.md" not in {p.name for p in views.registered_paths(repo)}
    assert "plugin-surface.md" in {p.name for p in views.registered_paths(REPO)}


def test_every_write_goes_through_the_generated_dir_guard(
    repo: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    rogue = views.ViewSpec(output_path=CAPTIONS_PATH, title="x", generator=views.VIEWS["readme"].generator)
    monkeypatch.setitem(views.VIEWS, "rogue", rogue)
    with pytest.raises(ValueError, match="authored sidecar"):
        views.write_views(repo, sqlite3.connect(repo / ".codemem/index.db"))
    assert json.loads((repo / CAPTIONS_PATH).read_text())["pkg/"] == "The package."


# ---------------------------------------------------------------------
# --check (AC2, AC3, AC4)
# ---------------------------------------------------------------------

def test_check_is_clean_right_after_write(repo: Path, capsys: pytest.CaptureFixture) -> None:
    _draw("--write")
    assert _draw("--check") == 0
    assert "OK" in capsys.readouterr().out


def test_hand_edit_on_line_2_is_drift_naming_the_remedy(repo: Path, capsys) -> None:
    _draw("--write")
    p = repo / "docs/architecture/component.md"
    lines = p.read_text().splitlines(keepends=True)
    lines[1] = "# Hand-edited\n"
    p.write_text("".join(lines))
    assert _draw("--check") == 1
    out = capsys.readouterr().out
    assert "component.md" in out and "codemem draw --write" in out


def test_a_different_valid_stamp_is_not_drift(repo: Path) -> None:
    """The sha and date are volatile; only the stamp's SHAPE is checked (§6.8 M6)."""
    _draw("--write")
    p = repo / "docs/architecture/README.md"
    rest = "".join(p.read_text().splitlines(keepends=True)[1:])
    p.write_text("<!-- generated by codemem draw @ abcdef1 on 2020-01-01 -->\n" + rest)
    assert _draw("--check") == 0


def test_a_mangled_stamp_is_drift(repo: Path, capsys) -> None:
    _draw("--write")
    p = repo / "docs/architecture/README.md"
    p.write_text("<!-- anything -->\n" + "".join(p.read_text().splitlines(keepends=True)[1:]))
    assert _draw("--check") == 1
    assert "stamp" in capsys.readouterr().out


def test_missing_view_is_drift(repo: Path) -> None:
    _draw("--write")
    (repo / "docs/architecture/component.md").unlink()
    assert _draw("--check") == 1


def test_readme_drift_is_caught(repo: Path) -> None:
    _draw("--write")
    p = repo / "docs/architecture/README.md"
    p.write_text(p.read_text() + "stray line\n")
    assert _draw("--check") == 1


@pytest.mark.parametrize("gone", [".codemem", "v2"])
def test_no_graph_is_unknown_and_exit_0(repo: Path, gone: str, capsys) -> None:
    _draw("--write")
    db = repo / ".codemem/index.db"
    if gone == "v2":
        sqlite3.connect(db).execute("PRAGMA user_version = 2").connection.close()
    else:
        db.unlink()
    assert _draw("--check") == 0
    assert "UNKNOWN" in capsys.readouterr().out


def test_caption_prose_edit_is_not_drift(repo: Path) -> None:
    _draw("--write")
    (repo / CAPTIONS_PATH).write_text(json.dumps({"@start": "pkg/a.py", "pkg/": "Reworded."}))
    assert _draw("--check") == 0


def test_start_edit_is_drift(repo: Path) -> None:
    _draw("--write")
    (repo / CAPTIONS_PATH).write_text(json.dumps({"@start": "lib/c.py", "pkg/": "The package."}))
    assert _draw("--check") == 1


def test_orphan_caption_fails_the_check(repo: Path, capsys) -> None:
    _draw("--write")
    caps = {"@start": "pkg/a.py", "pkg/": "The package.", "gone/x.py": "Deleted."}
    (repo / CAPTIONS_PATH).write_text(json.dumps(caps))
    _draw("--write")  # the diagrams are current; only the caption is stale
    assert _draw("--check") == 1
    assert "ORPHAN_CAPTION gone/x.py" in capsys.readouterr().out


def test_write_and_check_refuse_cut_options(repo: Path) -> None:
    for flags in (
        ("--write", "--level", "L2"), ("--check", "--scope", "pkg/"), ("--write", "--check"),
        ("--check", "--hops", "3"), ("--check", "--direction", "up"),
        ("--write", "--kind", "call"), ("--check", "--include-tests"),
    ):
        with pytest.raises(SystemExit) as exc:
            _draw(*flags)
        assert exc.value.code == 2


def test_bare_draw_still_prints_mermaid_to_stdout(repo: Path, capsys) -> None:
    assert _draw() == 0
    assert capsys.readouterr().out.startswith("flowchart LR\n")
    assert not (repo / "docs/architecture").exists()


# ---------------------------------------------------------------------
# §6.8 review fixes (M6)
# ---------------------------------------------------------------------

def test_hand_edit_inside_the_captions_block_is_drift(repo: Path) -> None:
    _draw("--write")
    p = repo / "docs/architecture/component.md"
    p.write_text(p.read_text().replace(views.CAPTIONS_OPEN, views.CAPTIONS_OPEN + "\n<img src=https://x.example/a>", 1))
    assert _draw("--check") == 1


@pytest.mark.parametrize("link", ["docs", "docs/architecture"])
def test_a_symlinked_output_dir_is_refused(repo: Path, tmp_path: Path, link: str) -> None:
    outside = tmp_path / "outside"
    (outside / "architecture").mkdir(parents=True)
    if link == "docs":
        caps = (repo / CAPTIONS_PATH).read_text()
        (repo / "docs" / CAPTIONS_PATH.split("/")[-1]).unlink()
        (repo / "docs").rmdir()
        (repo / "docs").symlink_to(outside)
        (outside / CAPTIONS_PATH.split("/")[-1]).write_text(caps)
    else:
        (repo / "docs/architecture").symlink_to(outside / "architecture")
    assert _draw("--write") == 1
    assert list((outside / "architecture").iterdir()) == []


def test_malformed_sidecar_reports_under_the_check_prefix(repo: Path, capsys) -> None:
    _draw("--write")
    (repo / CAPTIONS_PATH).write_text("{not json")
    assert _draw("--check") == 1
    assert "codemem draw --check:" in capsys.readouterr().err


def test_plugin_surface_names_from_file_stems_are_escaped(repo: Path) -> None:
    (repo / "claude-code/commands").mkdir(parents=True)
    (repo / "claude-code/commands/x`<img src=y>.md").write_text("Skill(nope)\n")
    (repo / "scripts").mkdir()
    (repo / "scripts/install.sh").write_text('AA_MA_HOOKS=(\n)\n')
    spec = views.VIEWS["plugin-surface"]
    body = spec.generator(repo, sqlite3.connect(repo / ".codemem/index.db"), {}, spec)
    assert "<img" not in body and "&lt;img" in body


def test_a_diagram_view_without_a_level_is_an_error(repo: Path) -> None:
    spec = views.ViewSpec("docs/architecture/x.md", "X", views.VIEWS["component"].generator)
    with pytest.raises(ValueError, match="level"):
        spec.generator(repo, sqlite3.connect(repo / ".codemem/index.db"), {}, spec)


# ---------------------------------------------------------------------
# CI (AC5)
# ---------------------------------------------------------------------

def test_security_workflow_has_an_architecture_drift_job() -> None:
    jobs = yaml.safe_load((REPO / ".github/workflows/security.yml").read_text())["jobs"]
    assert "architecture-drift" in jobs
    run = "\n".join(s.get("run", "") for s in jobs["architecture-drift"]["steps"])
    assert "codemem build" in run and "codemem draw --check" in run
    assert run.index("codemem build") < run.index("codemem draw --check")
